name: Deploy to Integration

on:
  push:
    branches:
      - integration

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.sdtecsolutions.com
          username: ${{ secrets.FTP_INT_USER }}
          password: ${{ secrets.FTP_INT_PASS }}
          server-dir: /public_html/integration/
