name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.sdtecsolutions.com
          username: ${{ secrets.FTP_STAG_USER }}
          password: ${{ secrets.FTP_STAG_PASS }}
          server-dir: /home/u679317752/domains/sdtecsolutions.com/public_html/staging
